# Generated by Django 3.0.8 on 2020-07-26 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_newscategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscategory',
            name='t_content',
        ),
        migrations.RemoveField(
            model_name='newscategory',
            name='t_header',
        ),
        migrations.AddField(
            model_name='news',
            name='news_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.NewsCategory'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
