# Generated by Django 3.0.8 on 2020-07-26 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200726_0943'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
