# Generated by Django 3.0.8 on 2020-07-26 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Picture',
        ),
    ]
