# Generated by Django 3.0.8 on 2020-07-27 19:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200727_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='t_content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='t_header',
        ),
        migrations.AddField(
            model_name='post',
            name='rt_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
