# Generated by Django 3.0.8 on 2020-07-27 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20200727_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='rt_content',
            new_name='content',
        ),
    ]
